name: SSB_test

 on:
   push:
     branches:
       - main

 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
 @@ -9,4 +14,4 @@ jobs:
         with:
           python-version: "3.8"
       - name: ğŸ³ Update dataset
         run: python ssb_test1.py
